image: node:12.15.0

pages:
  cache:
    paths:
    - node_modules/

  stage: deploy
  script:
  - npm install -g @angular/cli@9.0.4
  - npm install
  - ng build
  - ls -a
  - cp public/index.html public/404.html # Not necessary, but helps with https://medium.com/@pshrmn/demystifying-single-page-applications-3068d0555d46
  - mv public _public # CRA and gitlab pages both use the public folder. Only do this in a build pipeline.
  - mv build public # Move build files to public dir for Gitlab Pages
  artifacts:
    paths:
    - public
  only:
  - master
  - pages